config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "managements#index"
  resources :ingredients, only: [:index, :new, :create]
  resources :managements, only: [:index, :new, :create, :show, :destroy]
  resources :aims,        only: [:new, :create, :edit, :update]
  resources :posts do
    resources :comments, only: :create
  end
  resources :quizzes,     only: [:index, :new, :create]
end

app/models/aim.rb
class Aim < ApplicationRecord
  belongs_to :user

  with_options presence: true do
    validates :protein
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '肉' },
    { id: 3, name: '肉加工品' },
    { id: 4, name: '魚介' },
    { id: 5, name: '海藻' },
    { id: 6, name: '魚介加工品' },
    { id: 7, name: '卵' },
    { id: 8, name: 'いも' },
    { id: 9, name: '乳製品' },
    { id: 10, name: '大豆製品' },
    { id: 11, name: 'きのこ' },
    { id: 12, name: '豆' },
    { id: 13, name: '果物' },
    { id: 14, name: '野菜' },
    { id: 15, name: '主食' },
    { id: 16, name: 'おかず' },
    { id: 17, name: 'お菓子' },
    { id: 18, name: '飲み物' },
    { id: 19, name: '強化食品' },
    { id: 20, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :ingredients

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :text, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category

  with_options presence: true do
    validates :name
    validates :protein
    validates :calorie
  end

  validates :category_id, numericality: { other_than: 1 , message: "can't be blank"}
  
end

app/models/management.rb
class Management < ApplicationRecord
  belongs_to :user

  with_options presence: true do
    validates :name
    validates :protein
    validates :calorie
  end

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_one_attached :image

  validates :content, presence: { message: "or Image can't be blank"}, unless: :was_attached?

  def was_attached?
    self.image.attached?
  end

end

app/models/quiz.rb
class Quiz < ApplicationRecord

  with_options presence: true do
    validates :question
    validates :answer_1
    validates :answer_2
    validates :answer_3
    validates :answer_num
    validates :explain
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :nickname
    # validates :gender
    validates :birthday
  end
  validates :nickname, presence: true, length: { maximum: 6 }

  has_many :managements
  has_many :posts
  has_many :comments
  has_one :aim
end

app/controllers/aims_controller.rb
class AimsController < ApplicationController
  before_action :authenticate_user!

  def new
    @aim = Aim.new
  end

  def create
    @aim = Aim.new(aim_params)
    if @aim.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @aim = Aim.find(params[:id])
  end

  def update
    @aim = Aim.find(params[:id])
    if @aim.update(aim_params)
    redirect_to root_path(@aim.id)
    else
    render :edit
    end
  end


  private

  def aim_params
    params.require(:aim).permit(:goal, :protein, :calorie).merge(user_id: current_user.id)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @comment = Comment.create(comment_params)
    if @comment.save
      redirect_to "/posts/#{@comment.post.id}"
    else
      @post = @comment.post
      @comments = @post.comments
      render "/posts/show"
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def new
    @post = Post.new
  end

  def create

    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end

  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
  end
  
  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to root_path
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update

    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post.id)
    else
      render :edit
    end
  end


  private

  def post_params
    params.require(:post).permit(:image, :content).merge(user_id: current_user.id)
  end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :authenticate_user!

  def index
    @quiz = Quiz.all

    respond_to do |format|
      format.html
      format.json {render json: @quiz }
    end
  end

  def new
    @quiz = Quiz.new
  end

  def create
    Quiz.create(quiz_params)
    redirect_to new_quiz_path
  end

  private

  def quiz_params
    params.require(:quiz).permit(:question, :answer_1, :answer_2, :answer_3, :answer_num, :explain)
  end



end

app/helpers/aims_helper.rb
module AimsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/managements_helper.rb
module ManagementsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>PROTEIN</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="quiz.js"></script>
  </head>

  <body>
  <header>
  <nav class="navbar">
    <ul class="nav">
      <li class="nav-item">
        <%= link_to "Hello Protein", root_path, class: "nav-home" %>
      </li>
      <li class="nav-item">
        <%= link_to "Study", quizzes_path, class: "nav-item" %>
      </li>
    <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to "Post", new_post_path, class: "nav-item" %>
      </li>
      <li class="nav-item">
        <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-item" %>
      </li>
    <% else %>
      <li class="nav-item">
        <%= link_to "Login", new_user_session_path, class: "nav-item" %>
      </li>
      <li class="nav-item">
        <%= link_to "Signup", new_user_registration_path, class: "nav-item" %>
      </li>
    <% end %>
    </ul>
  </nav>
  
  </header>

    <%= yield %>

  <footer class="container">
    <p> Enjoy Your Life with PROTEIN APP. TK </p>
  </footer>

  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>