config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "managements#index"
  resources :ingredients, only: [:index, :new, :create]
  resources :managements, only: [:index, :new, :create, :show, :destroy]
  resources :aims,        only: [:new, :create, :edit, :update]
  resources :posts do
    resources :comments, only: :create
  end
  resources :quizzes,     only: [:index, :new, :create]
end

app/models/management.rb
class Management < ApplicationRecord
  belongs_to :user

  with_options presence: true do
    validates :name
    validates :protein
    validates :calorie
  end

end

app/controllers/managements_controller.rb
class ManagementsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    if user_signed_in?
    @protein = Management.where(user_id: current_user.id).where("created_at >= ?", Date.today).all.sum(:protein)
    @calorie = Management.where(user_id: current_user.id).where("created_at >= ?", Date.today).all.sum(:calorie)
    @aim = Aim.find_by(user_id: current_user.id)
    @management = Management.all
    @posts = Post.all.order("created_at DESC")
      
    end
  end

  def new
    @management = Management.new

    @ingredients = Ingredient.all
    @meats = Ingredient.where(category_id: 2)
    @processed_meats = Ingredient.where(category_id: 3)
    @fishes = Ingredient.where(category_id: 4)
    @seaweeds = Ingredient.where(category_id: 5)
    @processed_fishes = Ingredient.where(category_id: 6)
    @eggs = Ingredient.where(category_id: 7)
    @potatoes = Ingredient.where(category_id: 8)
    @dairy_products = Ingredient.where(category_id: 9)
    @soy_products = Ingredient.where(category_id: 10)
    @mushrooms = Ingredient.where(category_id: 11)
    @beans = Ingredient.where(category_id: 12)
    @fruits = Ingredient.where(category_id: 13)
    @vegetables = Ingredient.where(category_id: 14)
    @staples = Ingredient.where(category_id: 15)
    @sides = Ingredient.where(category_id: 16)
    @snacks = Ingredient.where(category_id: 17)
    @drinks = Ingredient.where(category_id: 18)
    @enriched_foods = Ingredient.where(category_id: 19)
    @others = Ingredient.where(category_id: 20)
  end

  def create
    @management = Management.new(management_params)
    if @management.save
      redirect_to root_path
    else
      render :new
    end

  end

  def show
    @managements = Management.where(user_id: current_user.id).where("created_at >= ?", Date.today)
  end

  def destroy
    management = Management.find(params[:id])
    management.destroy
    redirect_to management_path(management.id)
  end

  private

  def management_params
    params.require(:management).permit(:name, :protein, :calorie).merge(user_id: current_user.id)
  end

end

app/helpers/managements_helper.rb
module ManagementsHelper
end

app/views/managements/index.html.erb
<div class="container">
  <% if user_signed_in? %>
  <div class="title">
    <h2>My goal</h2>
    <% if @aim.present? %>
    <p><%= @aim.goal %></p>
    <% else %>
    <p>あなたの目標を設定しましょう</p>
    <% end%>
  </div>
  <div class="ingredient">
    <h2>Intakes for Today</h2>
    <div class="ingredient-wrapper">
      <div class="ingredient-protein">
        <p><%= "タンパク質：#{@protein.round(1)}/g" %></p>
        <% if @aim.present? %>
        <P><%= "目標：#{@aim.protein}g/日" %></p>
        <% else %>
        <P><%= "目標：_未設定_" %></p>
        <% end %>
      </div>

      <div class="ingredient-calorie">
        <p><%= "カロリー：#{@calorie.round(1)}/kcal" %></p>
        <div class="need-calorie">
        <% if @aim.present? %>
        <P><%= "必要量：#{@aim.calorie}kcal/日" %></p>
        <% else %>
        <P><%= "必要量：_未設定_" %></p>
        <% end %>
        </div>
      </div>
      <div class="button">
        <%= link_to("Add Intakes", new_management_path, {class: "btn btn--yellow btn--cubic"}) %>
        <% if @management.present? %>
        <%= link_to("Detail", management_path(@management.ids), {class: "btn btn--yellow btn--cubic"}) %>
        <% end %>
        <% if @aim.present? %>
          <%= link_to("Edit Goal", edit_aim_path(@aim), {class: "btn btn--yellow btn--cubic"}) %>
        <% else %>
          <%= link_to("Add Goal", new_aim_path, {class: "btn btn--yellow btn--cubic"}) %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="post">
    <h2>Our posts</h2>
    <div class="post-wrapper">
      <%= render partial: 'posts/post', collection: @posts%>
    </div>
  </div>
  <% else %>
  <div class="logout">
    <h2>Hello Protein</h2>
    <h3>~タンパク質で元気な体を作ろう~</h3>
    <p>Please signup or Login</p>
  </div>
  <% end %>
</div>

app/views/managements/new.html.erb
<div class="contents row">
  <div class="container">
    <h2>Add ingredients</h2>
    <%= form_with(model: @management, local: true) do |f| %>

      <%= render "shared/error_messages", model: f.object %>

      <%= f.text_field :name, placeholder: "put food-name", autofocus: true %>
      <%= f.text_field :protein, placeholder: "put protein" %>
      <%= f.text_field :calorie, placeholder: "put calorie" %>
      <%= f.submit "SEND" %>
    <% end %>
  </div>
</div>
<div class="container">
  <h1>タンパク質量一覧表(100gあたり)</h1>
  <% if @ingredients.present? %>
  <div class="ingredient-charts">
    <div class="ingredient-chart">
      <h2>肉</h2>
      <table class="line">
        <tr>
          <th class="line">Name</th>
          <th class="line">Protein</th>
          <th class="line">Calorie</th>
        </tr>
      <% @meats.each do |meat|%>
        <tr>
          <td class="line"><%= meat.name %></td>
          <td class="line"><%= meat.protein %></td>
          <td class="line"><%= meat.calorie %></td>
        </tr>
      <% end %>
      </table>
    </div>

    <div class="ingredient-chart">
      <h2>肉加工品</h2>
      <table class="line">
        <tr>
          <th class="line">Name</th>
          <th class="line">Protein</th>
          <th class="line">Calorie</th>
        </tr>
      <% @processed_meats.each do |processed_meat| %>
        <tr>
          <td class="line"><%= processed_meat.name %></td>
          <td class="line"><%= processed_meat.protein %></td>
          <td class="line"><%= processed_meat.calorie %></td>
        </tr>
      <% end %>
      </table>
    </div>

    <div class="ingredient-chart">
      <h2>魚介</h2>
      <table class="line">
        <tr>
          <th class="line">Name</th>
          <th class="line">Protein</th>
          <th class="line">Calorie</th>
        </tr>
      <% @fishes.each do |fish| %>
        <tr>
          <td class="line"><%= fish.name %></td>
          <td class="line"><%= fish.protein %></td>
          <td class="line"><%= fish.calorie %></td>
        </tr>
      <% end %>
      </table>
    </div>

    <div class="ingredient-chart">
      <h2>海藻</h2>
      <table class="line">
        <tr>
          <th class="line">Name</th>
          <th class="line">Protein</th>
          <th class="line">Calorie</th>
        </tr>
      <% @seaweeds.each do |seaweed| %>
        <tr>
          <td class="line"><%= seaweed.name %></td>
          <td class="line"><%= seaweed.protein %></td>
          <td class="line"><%= seaweed.calorie %></td>
        </tr>
      <% end %>
      </table>
    </div>

    <div class="ingredient-chart">
      <h2>魚介加工品</h2>
      <table class="line">
        <tr>
          <th class="line">Name</th>
          <th class="line">Protein</th>
          <th class="line">Calorie</th>
        </tr>
      <% @processed_fishes.each do |processed_fish| %>
        <tr>
          <td class="line"><%= processed_fish.name %></td>
          <td class="line"><%= processed_fish.protein %></td>
          <td class="line"><%= processed_fish.calorie %></td>
        </tr>
      <% end %>
      </table>
    </div>

    <div class="ingredient-chart">
      <h2>卵</h2>
      <table class="line">
        <tr>
          <th class="line">Name</th>
          <th class="line">Protein</th>
          <th class="line">Calorie</th>
        </tr>
      <% @eggs.each do |egg| %>
        <tr>
          <td class="line"><%= egg.name %></td>
          <td class="line"><%= egg.protein %></td>
          <td class="line"><%= egg.calorie %></td>
        </tr>
      <% end %>
      </table>
    </div>

    <div class="ingredient-chart">
      <h2>いも</h2>
      <table class="line">
        <tr>
          <th class="line">Name</th>
          <th class="line">Protein</th>
          <th class="line">Calorie</th>
        </tr>
      <% @potatoes.each do |potato| %>
        <tr>
          <td class="line"><%= potato.name %></td>
          <td class="line"><%= potato.protein %></td>
          <td class="line"><%= potato.calorie %></td>
        </tr>
      <% end %>
      </table>
    </div>

    <div class="ingredient-chart">
      <h2>乳製品</h2>
      <table class="line">
        <tr>
          <th class="line">Name</th>
          <th class="line">Protein</th>
          <th class="line">Calorie</th>
        </tr>
      <% @dairy_products.each do |dairy_product| %>
        <tr>
          <td class="line"><%= dairy_product.name %></td>
          <td class="line"><%= dairy_product.protein %></td>
          <td class="line"><%= dairy_product.calorie %></td>
        </tr>
      <% end %>
      </table>
    </div>

    <div class="ingredient-chart">
      <h2>大豆製品</h2>
      <table class="line">
        <tr>
          <th class="line">Name</th>
          <th class="line">Protein</th>
          <th class="line">Calorie</th>
        </tr>
      <% @soy_products.each do |soy_product| %>
        <tr>
          <td class="line"><%= soy_product.name %></td>
          <td class="line"><%= soy_product.protein %></td>
          <td class="line"><%= soy_product.calorie %></td>
        </tr>
      <% end %>
      </table>
    </div>

    <div class="ingredient-chart">
      <h2>きのこ</h2>
      <table class="line">
        <tr>
          <th class="line">Name</th>
          <th class="line">Protein</th>
          <th class="line">Calorie</th>
        </tr>
      <% @mushrooms.each do |mushroom| %>
        <tr>
          <td class="line"><%= mushroom.name %></td>
          <td class="line"><%= mushroom.protein %></td>
          <td class="line"><%= mushroom.calorie %></td>
        </tr>
      <% end %>
      </table>
    </div>

    <div class="ingredient-chart">
      <h2>豆</h2>
      <table class="line">
        <tr>
          <th class="line">Name</th>
          <th class="line">Protein</th>
          <th class="line">Calorie</th>
        </tr>
      <% @beans.each do |bean| %>
        <tr>
          <td class="line"><%= bean.name %></td>
          <td class="line"><%= bean.protein %></td>
          <td class="line"><%= bean.calorie %></td>
        </tr>
      <% end %>
      </table>
    </div>

    <div class="ingredient-chart">
      <h2>果物</h2>
      <table class="line">
        <tr>
          <th class="line">Name</th>
          <th class="line">Protein</th>
          <th class="line">Calorie</th>
        </tr>
      <% @fruits.each do |fruit| %>
        <tr>
          <td class="line"><%= fruit.name %></td>
          <td class="line"><%= fruit.protein %></td>
          <td class="line"><%= fruit.calorie %></td>
        </tr>
      <% end %>
      </table>
    </div>

    <div class="ingredient-chart">
      <h2>野菜</h2>
      <table class="line">
        <tr>
          <th class="line">Name</th>
          <th class="line">Protein</th>
          <th class="line">Calorie</th>
        </tr>
      <% @vegetables.each do |vegetable| %>
        <tr>
          <td class="line"><%= vegetable.name %></td>
          <td class="line"><%= vegetable.protein %></td>
          <td class="line"><%= vegetable.calorie %></td>
        </tr>
      <% end %>
      </table>
    </div>

    <div class="ingredient-chart">
      <h2>主食</h2>
      <table class="line">
        <tr>
          <th class="line">Name</th>
          <th class="line">Protein</th>
          <th class="line">Calorie</th>
        </tr>
      <% @staples.each do |staple| %>
        <tr>
          <td class="line"><%= staple.name %></td>
          <td class="line"><%= staple.protein %></td>
          <td class="line"><%= staple.calorie %></td>
        </tr>
      <% end %>
      </table>
    </div>

    <div class="ingredient-chart">
      <h2>おかず</h2>
      <table class="line">
        <tr>
          <th class="line">Name</th>
          <th class="line">Protein</th>
          <th class="line">Calorie</th>
        </tr>
      <% @sides.each do |side| %>
        <tr>
          <td class="line"><%= side.name %></td>
          <td class="line"><%= side.protein %></td>
          <td class="line"><%= side.calorie %></td>
        </tr>
      <% end %>
      </table>
    </div>

    <div class="ingredient-chart">
      <h2>お菓子</h2>
      <table class="line">
        <tr>
          <th class="line">Name</th>
          <th class="line">Protein</th>
          <th class="line">Calorie</th>
        </tr>
      <% @snacks.each do |snack| %>
        <tr>
          <td class="line"><%= snack.name %></td>
          <td class="line"><%= snack.protein %></td>
          <td class="line"><%= snack.calorie %></td>
        </tr>
      <% end %>
      </table>
    </div>

    <div class="ingredient-chart">
      <h2>飲み物</h2>
      <table class="line">
        <tr>
          <th class="line">Name</th>
          <th class="line">Protein</th>
          <th class="line">Calorie</th>
        </tr>
      <% @drinks.each do |drink| %>
        <tr>
          <td class="line"><%= drink.name %></td>
          <td class="line"><%= drink.protein %></td>
          <td class="line"><%= drink.calorie %></td>
        </tr>
      <% end %>
      </table>
    </div>

    <div class="ingredient-chart">
      <h2>強化食品</h2>
      <table class="line">
        <tr>
          <th class="line">Name</th>
          <th class="line">Protein</th>
          <th class="line">Calorie</th>
        </tr>
      <% @enriched_foods.each do |enriched_food| %>
        <tr>
          <td class="line"><%= enriched_food.name %></td>
          <td class="line"><%= enriched_food.protein %></td>
          <td class="line"><%= enriched_food.calorie %></td>
        </tr>
      <% end %>
      </table>
    </div>

    <div class="ingredient-chart">
      <h2>その他</h2>
      <table class="line">
        <tr>
          <th class="line">Name</th>
          <th class="line">Protein</th>
          <th class="line">Calorie</th>
        </tr>
      <% @others.each do |other| %>
        <tr>
          <td class="line"><%= other.name %></td>
          <td class="line"><%= other.protein %></td>
          <td class="line"><%= other.calorie %></td>
        </tr>
      <% end %>
      </table>
    </div>
    
  </div>
  <% end %>
</div>

app/views/managements/show.html.erb
<div class="container">
  <div class="management-detail">
    <% @managements.each do |management| %>
      <ul class="detail">
        <li class="detail-name"><%= management.name %></li>
        <li><%= "Protein：#{management.protein}" %></li>
        <li><%= "Calorie：#{management.calorie}" %></li>
        <li><%= link_to("Delete", management_path(management), method: :delete) %></li>
      </ul>
    <% end %>
  </div>
</div>